services:
  nginx:
    image: nginx:latest
    volumes:
      - ./src/:/var/www/
      - ./env/nginx/:/etc/nginx/conf.d
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - app-network
    container_name: secunda.test.nginx

  app:
    build:
      context: .
      dockerfile: env/app/Dockerfile
    volumes:
      - ./src:/var/www
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    container_name: secunda.test.app

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: secunda.db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3306
    ports:
      - "8090:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    networks:
      - app-network
    container_name: secunda.test.database


networks:
  app-network:
    driver: bridge